ALTER SESSION SET CONTAINER=XEPDB1;
CREATE USER taskproject IDENTIFIED BY juliangc;

ALTER USER taskproject QUOTA 100M ON USERS;
GRANT UNLIMITED TABLESPACE TO taskproject;


GRANT CREATE SESSION, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE MATERIALIZED VIEW TO taskproject;

GRANT INSERT ON taskproject.TASK TO taskproject;